name: Deploy React to WordPress

on:
  push:
    branches: [ react-frontend ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies and Build
      run: |
        npm install
        npm run build

    - name: Copy files to WordPress server via SCP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.WP_HOST }}
        username: ${{ secrets.WP_USER }}
        password: ${{ secrets.WP_PASS }}
        port: 22
        source: "build/*"
        target: "/var/www/html/wp-content/react"
